
// Mock data - replace with actual API call
export const mockCourses = [
   {
      id: "1",
      title: "Introduction to React",
      description: "Learn the basics of React development",
      instructor: "John Doe",
      category: "Programming",
      level: "Beginner",
      duration: "8 weeks",
      price: 99.99,
      isPublished: true,
      thumbnail: null,
      createdAt: new Date("2024-01-15"),
      updatedAt: new Date("2024-02-01"),
      students: 156,
   },
   {
      id: "2",
      title: "Advanced JavaScript",
      description: "Master advanced JavaScript concepts",
      instructor: "Jane Smith",
      category: "Programming",
      level: "Advanced",
      duration: "12 weeks",
      price: 149.99,
      isPublished: true,
      thumbnail: null,
      createdAt: new Date("2024-01-10"),
      updatedAt: new Date("2024-01-25"),
      students: 89,
   },
   {
      id: "3",
      title: "UI/UX Design Fundamentals",
      description: "Learn the principles of user interface design",
      instructor: "Mike Johnson",
      category: "Design",
      level: "Intermediate",
      duration: "6 weeks",
      price: 79.99,
      isPublished: false,
      thumbnail: null,
      createdAt: new Date("2024-02-01"),
      updatedAt: new Date("2024-02-15"),
      students: 0,
   },
   {
      id: "4",
      title: "Digital Marketing Strategy",
      description: "Complete guide to digital marketing",
      instructor: "Sarah Wilson",
      category: "Marketing",
      level: "Beginner",
      duration: "10 weeks",
      price: 129.99,
      isPublished: true,
      thumbnail: null,
      createdAt: new Date("2024-01-20"),
      updatedAt: new Date("2024-02-10"),
      students: 234,
   },
];